### ISSUE TITLE
Player creation cli

### ISSUE THREAD

**Issue by Paul92** [CruceGameDevel/CruceGame#106]
Add function to get input from user and create a Player.

**Comment by flavius** [comment]
Think about a homogenous and consistent way of registering commands for the CLI library to execute code from the game library.

http://en.wikipedia.org/wiki/Command_pattern - you don't have OOP.

**Comment by Paul92** [comment]
@danij suggested to implement the game logic inside cli library.

**Comment by danij** [comment]
I suggested implementing the UI logic inside the cli executable, which will then call the business logic from the main library. It's a subtle difference :)
