### ISSUE TITLE
Features, Requirements, Tools, Libraries

### ISSUE THREAD

**Issue by flavius** [CruceGameDevel/CruceGame#11]
Document (in this order):
- requirements (from the perspective of the user) - what will the user be able to do with your product (WHAT, not HOW)
- requirements - what operating systems will it run on? Which compilers and build infrastructure will you use?
- features - based on the requirements: what you will use to meet those requirements. Which testing framework will you use, will it be multithreaded, which networking techniques will you use (supposing "networking" is among the requirements), which UIs will be available, how will AIs be plugged into the game (supposing AI is a requirement)? "Features" should contain more technical details about how you meet the requirements, but without going into the details of "how"
- features - will there be a library which I can embed in my own UI? Is it going to be thread-safe?

**Comment by Paul92** [comment]
The documentation should provide the features and requrements for every version or just for the entire application (v.1.0.0)?

**Comment by flavius** [comment]
The requirements are sent to you by the client (but since you don't have one, you'll be your own client), so they're global. The features will also be generic at first, and you'll split it into milestones when everything has stabilized.

**Comment by Paul92** [comment]
This issue can be closed.
