### ISSUE TITLE
Is there a mailing list?

### ISSUE THREAD

**Issue by flavius** [CruceGameDevel/CruceGame#12]
- How will you communicate within the team?
- How will the client communicate with you?

Where is the mailing list? How to subscribe to it? Document it.

**Comment by RaduSzasz** [comment]
There is the Google+ Group created for communication amongst team members and as far as my opinion is concerned, there is no client to communicate with for now.

**Comment by flavius** [comment]
Please create a mailing list. Everyone has an e-mail, not so with google+ accounts.

E-Mails are also easy to back-up, to analyze, proprietary google+ posts are not.

Using e-mails the the professional way to go, social media is... well, for having fun, not for professional affairs.

**Comment by ghost** [comment]
Is http://notifylist.com/ a reasonable solution?

**Comment by Paul92** [comment]
We already have a mailing list at https://groups.google.com/forum/#!topic/cruce-development/LciBusQG4wI, with the adress cruce-development@googlegroups.com. I think this issue can be closed.
