### ISSUE TITLE
distributeDeck ambiguous

### ISSUE THREAD

**Issue by danij** [CruceGameDevel/CruceGame#126]
The purpose and/or name of the round_distributeDeck function is not clear to me.

**Comment by Paul92** [comment]
That function is used to distribute all cards from a deck to players at the
beginning of a round, before bidding. I guess its documentation should be
improved.
În data de 09.02.2014 11:26, "danij" notifications@github.com a scris:

**Comment by danij** [comment]
My fault, I misread a line of code
