### ISSUE TITLE
Coding Standard?

### ISSUE THREAD

**Issue by flavius** [CruceGameDevel/CruceGame#13]
Is your code following a coding standard? Is it documented? Is doxygen used or any other tool?

Describe such things in hacking.md

**Comment by RaduSzasz** [comment]
According to the vote on the ML, this issue has been solved.

**Comment by flavius** [comment]
How has it been solved?

_Is your code following a coding standard? Is it documented? Is doxygen used or any other tool?_
_Describe such things in hacking.md_

**Comment by RaduSzasz** [comment]
It has to be updated in hacking.md, indeed. I forgot about that. However, the authors have reached a decision upon using the Linux kernel coding standard.

How can I get assigned for completing the task?

**Comment by flavius** [comment]
@RaduSzasz Currently that can't be done, perhaps it will be done in the future by adding the developers directly in this project, and giving up using forks, but @danij will have to do that.

**However** I think that currently, it's better this way, because you're forced to communicate with your team.

"Getting credit" is already done, since the Authors are already listed in the documentation and the statistics can be built from the git history directly anyway - which has nothing to do with github.
