### ISSUE TITLE
libtool.m4

### ISSUE THREAD

**Issue by danij** [CruceGameDevel/CruceGame#179]
Is libtool.m4 supposed to be in the repo?

**Comment by sarvsav** [comment]
No, We don't require libtool.m4, as git doesn't allow empty directories to upload and we need m4 directory to build the m4 macros successfully (as part of autotools process) in the m4 directory, so we added m4 directory with empty libtool.m4, now another solution is that creating an m4 directory in autogen.sh script and completely remove the m4 directory.

**Comment by Paul92** [comment]
fixed in 1de9964
