### ISSUE TITLE
Restrict the choice to 11, 15 & 21

### ISSUE THREAD

**Issue by sarvsav** [CruceGameDevel/CruceGame#216]
In game points, user can enter any value. Better option to use Switch, and restrict the user to these fixed number of points.

**Comment by Paul92** [comment]
It is restricted in release build. For now, by default you get debug build, where you can choose any value. To get a release build, just remove -DDEBUG flag from src/Makefile.am.

**Comment by sarvsav** [comment]
Yes, i heard that there are two kinds of mode, in developer mode, you can modify the things, those are blocked in Release mode.
