### ISSUE TITLE
[Doc] Game Rules (Game Point System) (Both en/ro versions)

### ISSUE THREAD

**Issue by sarvsav** [CruceGameDevel/CruceGame#29]
In case of game rules, romanian version: 

"Sa zicem ca ne continuam jocul in 4 lasat la scorul de 2 - 9 si acelasi jucator al primei echipe castiga licitatia cu doua. La finalul turei, se numara punctele si prima echipa a acumulat 102 puncte, iar cea de-a doua 18. Scorul va fi 5 - 9 (A se observa diferenta fata de whist unde daca nu faci exact cat ai licitat, iei minus, si toti jucatorii au pariurile lor, neexistand un singur pariu pentru fiecare tura)."

I think the final score should be 4-9, instead of 5-9. Because the bid made by first team player was of two. As It's written there that they scored 109 points too, So does it make the increment of 3? 

Does the point matters or the bidding matters? In my opinion, it should be bidding, so the final score must be 4-9 instead of 5-9.

**Comment by RaduSzasz** [comment]
The score will be 5-9. This example was meant to illustrate that there is no problem if someone goes over the bid and it is something like "The more, the better".

**Comment by flavius** [comment]
Can I close this?

**Comment by RaduSzasz** [comment]
I am working on formatting and doing a check right now.
