### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by flavius** [CruceGameDevel/CruceGame#35]
Analyze the features and the requirements and create a roadmap for the five milestones: 0.2.0, 0.4.0, 0.6.0, 0.8.0, 1.0.0.

Since you're currently working on 0.2.0, try to create a finer-grained task list (or better yet, a tree of tasks with depencies as children) for this milestone.

**Comment by Paul92** [comment]
The development releases (0.2.0, 0.4.0, 0.6.0, 0.8.0) should provide a functional software, meaning that should allow users to play the game, even if some features are not implemented (meaning that they must have some ui) or there may be just the buisiness logic of the application (at least in v0.2.0)?

**Comment by flavius** [comment]
Yes. And all tests should pass.
