### ISSUE TITLE
Implement basic data structures

### ISSUE THREAD

**Issue by Paul92** [CruceGameDevel/CruceGame#46]
Implement data structures documented in docs/data-structures.md, as well as some helper functions (like addPlayer to a team). That is just a reference, feel free to add/remove from it.
Comment often, use IRC to let other know what are you doing/what have you done. Work as a team.

**Comment by Paul92** [comment]
I shall start working on Card and Deck.

**Comment by danij** [comment]
I would not store the socket fd in the player structure, but create a special structure just for that information. That structure could also store the ip address, and other network related information and be defined in network.h or simi

As the networking API is not (100%) cross-platform, network.h would have quite a few #ifdef's and this strategy would restrict them to only be present in network.h/.c, and not in 100 other source files.

**Comment by Paul92** [comment]
I shall start working on round and hand structures.

**Comment by flavius** [comment]
@Paul92 I have randomly tasked @MarianG with this. Please find a way to cooperate in order to get the best technical solution, **no ego involved**.

Please do not forget about feature branches. Push them to origin. Your progress must be publicly visible.

**Comment by Paul92** [comment]
Well, I have done just a basic skeleton.
I would like all team members join IRC (at least while they are working) to share their progress, ask for help if it is needed and debate issues that arise.
Also, do not think the code written is good. There is much more to improve and to add.

**Comment by Paul92** [comment]
Fixed in 65f7be6 (Hand and Round structures), d85d24b (Player and Team structures), 46ce7c4 (Card and Deck structures), 0dba723 (Game strucure).
