### ISSUE TITLE
Rethink static variables 

### ISSUE THREAD

**Issue by Paul92** [CruceGameDevel/CruceGame#47]
Find a way to avoid the use of static variables in createPlayer and createTeam, if possible.

**Comment by Paul92** [comment]
As we use dynamic allocation, the actual pointer may be used for identification, so there is no need for id's. Delete them.

**Comment by flavius** [comment]
Are you sure? I haven't read the code, but: what if you want to reallocate it or search for a common identificator of a player or team?

Or what if you want to suspend a game (serialize/deserialize), or pass control over from a player to another? The players and the teams will not sit at the same RAM address across all PCs involved in the game.

I would be cautious about identifying chucks of data based on the RAM address in a way which interferes with the application domain. RAM addresses are for programmers, IDs are for the application domain - in 99.99% of the cases you don't want to mix those two usages.

**Comment by Paul92** [comment]
Right, I forgot the networking :D. 
But still, something must be done. Maybe request the id at initialization?

**Comment by flavius** [comment]
@RaduSzasz is assigned, let's hear his proposal.

**Comment by Paul92** [comment]
The static id's will be removed. They are overengineered for current needs.
