### ISSUE TITLE
struct ... VS typedef struct {} ... 

### ISSUE THREAD

**Issue by danij** [CruceGameDevel/CruceGame#48]
Which of the two should be used in the project?
It all comes down to having to write "struct" everytime the structure is referenced, or not.

**Comment by Paul92** [comment]
Using struct keyword makes it more obvious that it is a user-defined structure. I do not consider this a too much overhead.

**Comment by sarvsav** [comment]
We would prefer to use struct keyword. keep the things clear.

**Comment by ghost** [comment]
writing "struct" everytime makes you aware of certain things
