### ISSUE TITLE
Unicode strings

### ISSUE THREAD

**Issue by danij** [CruceGameDevel/CruceGame#49]
Will unicode string be supported?
If so, which encoding will be used?

**Comment by Paul92** [comment]
If they are to be used, this will happen in a latter version (anyway, not v0.2.0).

**Comment by sarvsav** [comment]
Yes, better keep the things simple for ver 0.2.0

**Comment by Paul92** [comment]
We decided to use unicode in v0.2.0, because of the characters for card suits. The folowing versions will have unicode support too. The encoding used is UTF-8.

**Comment by flavius** [comment]
I would suggest getting a 0.2.0 ready without unicode. You could use ASCII letters for now.

**Comment by Paul92** [comment]
Well, ASCII doesn't support characters for card suits (at least not in a
portable manner). But, for v0.2.0 this is the only place where Unicode has
to be used. By v1.0.0 we must have full Unicode support.
În data de 02.02.2014 09:34, "Flavius Aspra" notifications@github.com a
scris:
