### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by flavius** [CruceGameDevel/CruceGame#50]
At commit d85d24b93b1e4e621f0, entering `./autogen.sh` says 

```
aclocal: error: 'configure.ac' is required
Failed aclocal
```

The documentation is completely missing on how to get this rolling.

**Comment by Paul92** [comment]
I have added the file required. Now please write some documentation about the build process (tools required and involved steps).

**Comment by sarvsav** [comment]
Fixed.

**Comment by flavius** [comment]
@sarvsav You have solved the issue on a feature branch, but according to the development model you have documented, you haven't yet merged it back into develop.

You must do so, so that future features started off the develop branch include this fix, so there will be less (or none) merge conflicts when you're done with a milestone.

**Comment by Paul92** [comment]
I told him not to merge into develop yet, to test on my machine too. I
shall test it tonight and tell sarvsav to merge the branches.

**Comment by flavius** [comment]
When an user files in a bug report, you should also ask him to try the new version (in this case, to try the new build instructions) and ask him for further details if it still does not work for him.

Do not mark issues as solved and close them unless you're really sure they're solved.

**Comment by Paul92** [comment]
The issue is not fixed at all.
Firstly, there are some advices you get when running autogen.sh. Please investigate them.
Secondly, the issue was about the lack of build documentation too, not only about some warnings.

**Comment by Paul92** [comment]
I think we fixed the bulid issues and added build instructions in README.md. Please review.

**Comment by flavius** [comment]
The patch works for me.
