### ISSUE TITLE
Tests to not run under OS X without a make install as root

### ISSUE THREAD

**Issue by danij** [CruceGameDevel/CruceGame#64]
./run-test.sh 

*\* (cutter:34966): WARNING **: can't load a shared object for test case: ./.libs/test_team.so: dlopen(./.libs/test_team.so, 1): Library not loaded: /usr/local/lib/libdeck.0.dylib
  Referenced from: /Volumes/SoftwareDocumentation/Projects/CruceGame/test/.libs/test_team.so
  Reason: image not found

*\* (cutter:34966): WARNING **: can't load a shared object for test case: ./.libs/test_round.so: dlopen(./.libs/test_round.so, 1): Library not loaded: /usr/local/lib/libdeck.0.dylib
  Referenced from: /Volumes/SoftwareDocumentation/Projects/CruceGame/test/.libs/test_round.so
  Reason: image not found

*\* (cutter:34966): WARNING **: can't load a shared object for test case: ./.libs/test_deck.so: dlopen(./.libs/test_deck.so, 1): Library not loaded: /usr/local/lib/libdeck.0.dylib
  Referenced from: /Volumes/SoftwareDocumentation/Projects/CruceGame/test/.libs/test_deck.so
  Reason: image not found

Finished in 0.000056 seconds (total: 0.000000 seconds)

0 test(s), 0 assertion(s), 0 failure(s), 0 error(s), 0 pending(s), 0 omission(s), 0 notification(s)
0% passed

**Comment by Paul92** [comment]
Have you tried `make check`?

**Comment by Paul92** [comment]
Try setting LD_LIBRARY_PATH environment variable to your working directory.
