### ISSUE TITLE
Rename MAX_PLAYERS to MAX_PLAYERS_IN_TEAM

### ISSUE THREAD

**Issue by danij** [CruceGameDevel/CruceGame#77]
Rename MAX_PLAYERS to MAX_PLAYERS_IN_TEAM to remove ambiguity

**Comment by Paul92** [comment]
It wouldn't be better if we create a constants.h to put this kind of constants?

**Comment by danij** [comment]
It would

**Comment by danij** [comment]
Still writes MAX_PLAYERS
