### ISSUE TITLE
compare cards

### ISSUE THREAD

**Issue by Paul92** [CruceGameDevel/CruceGame#81]
Write a function for card comparison. Take into account the trump.

**Comment by flavius** [comment]
Why has this been closed?

**Comment by Paul92** [comment]
It has been fixed in d92fa13

**Comment by danij** [comment]
```
if (card1->value == 0)
    valueCard1 = 9;
```

should be the other way round. A card of "9" has 0 value

**Comment by Paul92** [comment]
It's fine. We use game values for cards, not face values.

**Comment by danij** [comment]
Why is that? 
I've noticed that if he compares IV to IX, IX comes out as a winner.

**Comment by Paul92** [comment]
Yes, because when comparing cards you care about the face value. But that is the only point when you care about that (and when displaying the card); in rest, you use game value for computing score and things like that.

**Comment by danij** [comment]
This is silly, because if the function were to be used just for sorting the cards for display, the trump parameter would be useless.
Also, when I hold the cards in my hands, I usually place the IX's at the end, before the 2's

**Comment by Paul92** [comment]
Well, somewhere must be made a conversion, either way. What's the difference if
we convert game value to face value and if we convert face value to game value?
Also, deck_compareCards is meant to compare cards in the context of a hand. To sort them for display, basic comparison operators may be used.

**Comment by ghost** [comment]
We discussed this issue on IRC and mail  long time ago.
He said something about business logic and how it should be separate form visual logic, I could not disagree.

**Comment by danij** [comment]
In the end is was not about visual logic, they just misunderstood a rule of the game.

**Comment by Paul92** [comment]
Well, it was about visual logic. It seems I knew that rule when I have choosen that constant, and it does separate the visual logic and business logic (because we don't care about the face value until we display the card).
